### PR TITLE
Update RectangleIntersectionTest.cpp

### PR DESCRIPTION
**Pull request by Komzpa**
Trac: https://trac.osgeo.org/geos/ticket/865

### CODE REVIEW

**Comment by Komzpa** [comment]
Source: https://github.com/postgis/postgis/pull/202

**Comment by dbaston** [comment]
@Komzpa you [mentioned](https://github.com/postgis/postgis/pull/268#discussion_r202702631) that you have an infinite loop failure in `GEOSClipByRect`. Is this test supposed to produce that failure? (I don't get an infinite loop)

**Comment by Komzpa** [comment]
The more direct option to catch the test cases would be to revert lwgeom_clipbybox2d to use GEOS and make subdivide tests pass, they generated different failures depending on pivot selection algorithm and whether points align with boundary.

**Comment by Komzpa** [comment]
This commit reproduces the hang:
https://github.com/postgis/postgis/pull/202/commits/5b777a5ae35c45efef3b47fbfe6fa69da32516b6

hanging builds: https://travis-ci.org/postgis/postgis/builds/336175244

**Comment by dbaston** [comment]
Do you have an input to `GEOSClipByRect` that fails?

**Comment by dbaston** [comment]
Closing this for now; please re-open (or create a new issue) if you're able to reproduce the failure.

**Pull request closed without merging**
