### PR TITLE
Add GEOSEqualsIdentical C API function for checking binary equivalence

### PR DESCRIPTION
**Pull request by dbaston**
This PR adds a C API function `GEOSIdentical` that determines if two geometries are ~binary-equivalent~ pointwise-equivalent. It is distinct from other predicates such as `GEOSEquals` (which uses topological equality, returning `true` for different representations of the same structure) and `GEOSEqualsExact` (which uses pointwise equality, but allows for a distance tolerance and ignores Z/M values). This also differs from the above functions in applying a test of binary equivalence (NaN = NaN) rather than numeric equality (NaN != NaN).

I think there may _also_ be a place for some kind of `GEOSEqualsExactDims(int dims, double tol)` function that allows you to specify which dimensions you're interested in, but for the common case of "tol = 0, dims = ALL" it is worthwhile to have a specific function that can use a more efficient implementation.

### CODE REVIEW

**Comment by dbaston** [comment]
Name suggestion from Slack: `GEOSEqualsIdentical`

**Comment by dbaston** [comment]
@jorisvandenbossche , would this provide a solution for https://github.com/shapely/shapely/issues/1732 ?

**Comment by jorisvandenbossche** [comment]
I think so, yes, at least in idea (on the short term we will need to have a fallback anyway for released GEOS vesions). 

For the exact behaviour details: naively (and based on the current docs), I would expect that `GEOSEqualsExact(geom, tolerance=0)` and `GEOSEqualsIdentical(geom)` to be equivalent (minus the dimension issue). 

But because of the implementation details of using `memcmp` that's not exactly the case. As far as I understand (no floating point expert, just googled it ;)), the bit-by-bit comparison for floats has the following consequences:

- NaNs also compare equal if they are in the same location in both geometries. I think this is something we want for this function? (and contrasts it with GEOSEqualsExact, which will return False when comparing for example `"POINT (1 NaN)"`) 
- My [understanding](https://stackoverflow.com/questions/25808445/why-cant-the-floating-point-types-compare-by-using-memcmp-function#comment40373249_25808698) is that, generally, bit-by-bit comparison will give the same as `==` for floats, with the exception of two cases: zeroes and NaNs. It's OK that NaNs compare equal (bullet point above), but you have different NaN representations that will then not compare equal (I don't know how easy it would be to end up with that through operations in GEOS). But -0.0 ad +0.0 also have different bit representation (and so would make GEOSEqualsIdentical return False), and I assume this is certainly possible to end up with in GEOS (eg reduce precision of two different geoms and then check if they are identical). 

Using the `memcmp` certainly gives an easier implementation (and faster), just wondering about the (potentially confusing) corner cases it might introduce.

**Comment by dbaston** [comment]
Thanks for the feedback. Like you, I'm not worried about considering quiet and signaling NaNs to be distinct. And the only way to get a signaling NaN is by deliberately creating one. But I think the behavior with signed zeros would be a problem. I've removed the `memcmp` usage so that +/- 0.0 are equivalent. A side effect is that different NaNs are also now equivalent.

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
