### PR TITLE
tests: geos_unit: fix missing include

### PR DESCRIPTION
**Pull request by metux**
Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>

### CODE REVIEW

**Comment by dbaston** [comment]
What platform is affected? The file already includes `cstdlib`

**Comment by metux** [comment]
> What platform is affected? The file already includes `cstdlib`

SLES12. 

Havent checked other distros yet.

**Comment by dbaston** [comment]
What is undefined without the include? `EXIT_SUCCESS` ?

**Comment by pramsey** [comment]
@metux can you address? I also don't see why `cstdlib` isn't sufficient.

**Pull request closed without merging**
