### PR TITLE
Autotools: Add the std=c++11 to the flags automatically

### PR DESCRIPTION
**Pull request by Algunenano**
Since I was there it also removes several macros that are no longer used.

### CODE REVIEW

**Comment by Algunenano** [comment]
Does this change require any improvements to be considered?

**Comment by dbaston** [comment]
I'm not using autotools so not in a position to evaluate it. Maybe @strk could check it out?

**Comment by strk** [comment]
Merged as f5131cf06e2204de0176fae7fe2245548cad04ad

**Comment by Algunenano** [comment]
Thanks!

**Pull request closed without merging**
