### PR TITLE
Use CoordinateXY type for TopologyValidationError

### PR DESCRIPTION
**Pull request by dbaston**

### CODE REVIEW

**Comment by dr-jts** [comment]
Validity is only checked in the XY plane.  So it's actually more appropriate if only XY is used for the location report.

**Comment by dbaston** [comment]
I agree that 2D is better but the longstanding output is not _wrong_, so it doesn't seem desirable to change it.

**Comment by pramsey** [comment]
I guess, but it's also only a message? Hard call. Like you said on the PostGIS ticket, at some level downstream shouldn't be spending a lot of effort testing the underlying library at very fine granularity?

**Comment by dbaston** [comment]
OK, so change the message and change the  `TopologyValidationError` class to use the `CoordinateXY` type?

**Comment by dr-jts** [comment]
> OK, so change the message and change the `TopologyValidationError` class to use the `CoordinateXY` type?

+1

**Comment by pramsey** [comment]
Yes, onwards to our glorious future!

**Pull request merged**
