### PR TITLE
CMakeLists.txt: add BUILD_BENCHMARKS

### PR DESCRIPTION
**Pull request by ffontaine**
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by dbaston** [comment]
Out of curiosity, is there some problem the benchmarks are causing?

**Comment by ffontaine** [comment]
Yes, they raise some build failures on buildroot autobuilders:

```
[100%] Linking C executable ../../bin/perf_memleak_mp_prep
/home/giuliobenetti/autobuild/run/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/riscv64-buildroot-linux-musl/9.2.0/../../../../riscv64-buildroot-linux-musl/bin/ld: warning: libgeos.so.3.9.0, needed by ../../lib/libgeos_c.so.1.16.2, not found (try using -rpath or -rpath-link)
```

Full build logs can be found here: http://autobuild.buildroot.org/?reason=libgeos%

I'm not able to reproduce them on my machine with cmake 3.18.4 so I think that these build failures are only raised with "old" cmake (e.g. 3.15.5).

Because buildroot targets embedded linux systems, it makes sense to just disable benchmarks for the moment.

**Comment by dbaston** [comment]
I think the issue is that `perf_memleak_mp_prep` links to `geos_c` only:

https://github.com/libgeos/geos/blob/546f7846f548cbcafe65605f95641aa40f7db443/benchmarks/capi/CMakeLists.txt#L18

which would be OK if `geos_c` had `PUBLIC` linkage to `geos`, but instead it is `PRIVATE`:

https://github.com/libgeos/geos/blob/546f7846f548cbcafe65605f95641aa40f7db443/CMakeLists.txt#L260

I think the right fix here is to use `PUBLIC` linkage, since anything that links to `geos_c` must also link to `geos`.

**Comment by ffontaine** [comment]
Indeed, this could fix the build failure. Still, do you think it would also make sense to merge this PR?

**Comment by dbaston** [comment]
I'm fine with it. It sounds like you need it in the stable 3.9 branch?

**Comment by ffontaine** [comment]
Yes, it would be perfect if you could add it in the stable 3.9 branch.

**Pull request merged**
