### PR TITLE
Fix Delaunay robustness by using longer floating point variable

### PR DESCRIPTION
**Pull request by Komzpa**
GEOS ticket: https://trac.osgeo.org/geos/ticket/922#ticket

PostGIS ticket: https://trac.osgeo.org/postgis/ticket/4152

### CODE REVIEW

**Comment by dbaston** [comment]
Long double is 64 bits in MSVC; I think you need to ifdef out the test.

**Comment by Komzpa** [comment]
@dbaston is there a chance to get it into 3.7.0 and backpatch to 3.6 before release of 3.7? :)

**Comment by dbaston** [comment]
I think so. You said on the JTS ticket that you had reduced the failure case to a 5-point input; can you use that here?

**Comment by dbaston** [comment]
@Komzpa ^^^

**Comment by dbaston** [comment]
@Komzpa Great! Can you please squash the commits and force-push?

**Comment by Komzpa** [comment]
done. isn't there squash-and-merge button on github PR merge though, why is it manual?

**Comment by dbaston** [comment]
This is just a mirror of the GEOS repository.

**Pull request merged**
