### PR TITLE
CI: Migrate MacOS and cppcheck to GitHub, remove Azure pipelines

### PR DESCRIPTION
**Pull request by dbaston**

### CODE REVIEW

**Comment by pramsey** [comment]
I like having fewer CI, but one of the nice things about the AZ one was the really intense compiler coverage. Wonder if some of those old setup recipes from the AZ file could be brought along, that pull old chains from `ppa:ubuntu-toolchain-r/test`

**Comment by dbaston** [comment]
Yes, I can add them back in.

**Comment by dr-jts** [comment]
Can Azure be removed from the GEOS doc [page](http://libgeos.org/development/ci_status/)?

**Comment by pramsey** [comment]
Yep, it's no longer being run since the .azure file is gone.

**Comment by dr-jts** [comment]
Done!

**Pull request merged**
