### PR TITLE
Change MultiPoint WKT to use parentheses in sub-members

### PR DESCRIPTION
**Pull request by mwtoews**
This is a potentially breaking change that switches the WKT output of MultiPoint from:

    MULTIPOINT (2 8, 3 9)

to

    MULTIPOINT ((2 8), (3 9))

This aligns with JTS' outputs of MultiPoint and with ISO/OGC specs.

See also https://github.com/postgis/postgis/pull/682 which was implemented for PostGIS 3.3

### CODE REVIEW

**Comment by pramsey** [comment]
I wonder how many downstream projects have tests against the WKT output of MULTIPOINT.

**Comment by mwtoews** [comment]
Possibly a few, for instance I'll try shapely later. Another strategy is to modify WKTWriter to enable an option, keeping the default to use old behaviour.

**Comment by dr-jts** [comment]
> I wonder how many downstream projects have tests against the WKT output of MULTIPOINT.

I think we have to note this as a breaking change and move on.  It's more important to be standards-compliant.

**Comment by dr-jts** [comment]
`WKTReader` can still handle both forms, right?

It's good to update the unit tests that aren't specifically checking this behaviour.  But are there still tests for `WKTReader` that check both formats?

**Comment by mwtoews** [comment]
> `WKTReader` can still handle both forms, right?

Yes, and I intentionally left a few test cases with the previous form. The only exception that I'm aware of #902 which will be closed as "not planned".

**Pull request merged**
