### PR TITLE
Fix MonotoneChainBuilder::getChain with empty CoordinateString

### PR DESCRIPTION
**Pull request by strk**
See https://github.com/libgeos/geos/issues/539

### CODE REVIEW

**Comment by strk** [comment]
I'm also moving a test which was previously found in the MonotoneChainBuilderTest.cpp file into a better named Geometry/differenceTest.cpp file (\cc @pramsey)

**Comment by strk** [comment]
The new test is found to segfault in the 3.9 branch (didn't test in main branch yet, CI will)

**Comment by strk** [comment]
Nicely: the testcase segfaults in main branch too

**Comment by dbaston** [comment]
This is testing a null `CoordinateSequence`, not an empty `CoordinateSequence`. Am I missing something?

**Comment by strk** [comment]
@dbaston yes, sorry, now updated (force-pushed) to test an empty one.

**Comment by strk** [comment]
main branch is NOT crashing at ::getChains, just returning an unexpected vector of 1 chain rather than 0 chains (as I'd expect). It still crashes afterwards though, when calling getEnvelope on that single (empty) chain.

**Comment by dbaston** [comment]
Let me know if you want me to fix it. I would probably just guard against `m_i == 0` in `finishChain`

**Comment by strk** [comment]
> Let me know if you want me to fix it. I would probably just guard against `m_i == 0` in `finishChain`

Thanks, I'll take care of it. Will just ping you for review when I'm happy with my changes

**Pull request merged**
