### PR TITLE
Normalize CMake with cmakelint

### PR DESCRIPTION
**Pull request by mwtoews**
This PR does not change any functionality of CMake (or at least I hope not). It's intended to make these files more consistent, and using modern-ish CMake conventions.

Most of these changes were found with [cmakelint](https://github.com/richq/cmake-lint):
```bash
$ pip install cmakelint
$ git ls-files '*CMakeLists.txt' | xargs cmakelint
$ git ls-files '*.cmake' | xargs cmakelint
```
Several of these were ignored, where it seems fragile commands should not be split. Also, while macro names are normally lowercase, I kept `GenerateSourceGroups` rather than using a less readable `generatesourcegroups`.

### CODE REVIEW

**Comment by strk** [comment]
Hey Mike, would you force-push a rebase of this PR ? I'd like to test a new configuration in github (activated hosted Drone CI: https://cloud.drone.io/libgeos/geos)

**Comment by pramsey** [comment]
I'm fine with this. Note we'll probably be tossing most of this CMake infra infavour of a "truly modern" implementation during the sprint in a couple weeks.

**Comment by mwtoews** [comment]
@strk I'm not sure if I understand what you mean to force-push a rebase, since it has no conflicts with the base branch.
@pramsey yes, I'm aware that a "modern cmake" revamp is imminent, as discussed somewhere here a few months ago. Looking forward to seeing it!

**Comment by pramsey** [comment]
Since modern cmake landed last week, should this be closed and re-run against the new state?

**Comment by mwtoews** [comment]
Keep this open. I'll just redo some of this on the new master and `push -f` here. The new CMake files are much nicer to see, and won't require as many modifications.

**Comment by mloskot** [comment]
@mwtoews It may be sensible to dedicate one Travis for non-build tasks: linting CMake files, making and linting docs (any Markdown files there?), linting YAML files, etc.

**Comment by pramsey** [comment]
Since we changed all the cmake files I'm closing this one out for now.

**Pull request closed without merging**
