### PR TITLE
Move tests/perf to new benchmarks directory

### PR DESCRIPTION
**Pull request by mloskot**
Move tests/perf to new benchmarks directory

As perf programs are not intended for execution as part of tests,
they already have been filtered out. Reflecting this fact in code
structure seems appropriate.

Additionally, rationalise names of `add_test`-created tests as
`test_{unit|xml}` to clear confusion with target names of executable
and remove superfluous `geos` part.

----

/cc @dr-jts

### CODE REVIEW

**Comment by dr-jts** [comment]
Looks good - thanks.

**Comment by mloskot** [comment]
@dr-jts Care to merge?

**Comment by dbaston** [comment]
@dr-jts I use this procedure:

```
git remote add mloskot https://github.com/mloskot/geos # just once
git fetch mloskot
git checkout master
git merge mloskot/ml/move-perf-to-benchmark
git push
```

**Comment by mloskot** [comment]
Shoot, I constantly forget the non-automatic way is required :-(

**Comment by dbaston** [comment]
I should script it; I think the mess that would be created if two people tried to merge at the same time

**Comment by dbaston** [comment]
Unfortunately all the autotools files have to be updated for this to go in master

**Comment by mloskot** [comment]
Hell, I completely forgot! I may get it done later tonight

**Comment by mloskot** [comment]
@dbaston autotools done

**Comment by pramsey** [comment]
Merged

**Comment by mloskot** [comment]
@pramsey Thank you!

**Pull request closed without merging**
