### PR TITLE
Fix minor stylistic flaws

### PR DESCRIPTION
**Pull request by nilason**
This fix addresses:

- bad indentation on some comment blocks
- add space before doxygen tags
- remove doxygen comment block style (/**) from in-code comment blocks
- trailing spaces in ttmath

If you think we should not poke around in ttmath, I’ll revoke that part.

(this PR is a mirror of https://git.osgeo.org/gitea/geos/geos/pulls/98)

### CODE REVIEW

**Comment by dbaston** [comment]
Is this the result of some automated formatting command?

**Comment by nilason** [comment]
> Is this the result of some automated formatting command?

No, not directly. They are mainly artefacts/fixes, manually fixed (except the trailing whitespace), discovered while working on a doxygen comment style converter script.

**Comment by dbaston** [comment]
Could you please back out the changes to `ttmath` ? Otherwise, looks good to me.

**Comment by nilason** [comment]
> Could you please back out the changes to ttmath ? 

No problem. Ttmath changes removed.

**Pull request merged**
