### PR TITLE
Add Coordinate::distanceSquared

### PR DESCRIPTION
**Pull request by dbaston**
This can be used to shave some time off minimum distance calculations.

Shaves about 10% off the test suite time for me.

### CODE REVIEW

**Comment by strk** [comment]
I'm pretty sure I remember having seen, years ago, a user report
which made the squared distance overflow. Please keep this in mind,
in case you can think of a way to handle such case.

**Comment by dr-jts** [comment]
> I'm pretty sure I remember having seen, years ago, a user report which made the squared distance overflow. Please keep this in mind, in case you can think of a way to handle such case.

I don't see how overflow can be more of a problem using dist^2 than dist.  Distance is always computed by first computing the distance^2, and then taking the square root.  So if the distance^2 overflows, the square root will be erroneous as well.

**Comment by Algunenano** [comment]
> I don't see how overflow can be more of a problem using dist^2 than dist. Distance is always computed by first computing the distance^2, and then taking the square root. So if the distance^2 overflows, the square root will be erroneous as well.

A guild scenario, but I'm not sure if it's possible with square root, `(a^2 + b^2)` is computed using 80bit registers and the result overflows a 64b double; then calculating the sqrt before returning could avoid the overflow (provided the cpu used a 80bit sqrt operation).

In any case, that'd be architecture and CPU dependant so I wouldn't consider it important.

**Comment by dr-jts** [comment]
@dbaston is much of the performance boost due to the switch to `std::array` from `std"vector`?

**Comment by dbaston** [comment]
> @dbaston is much of the performance boost due to the switch to `std::array` from `std::vector`?

I don't think it was, but I could be wrong. Sorry for not documenting it at the time.

**Comment by strk** [comment]
> I don't see how overflow can be more of a problem using dist^2 than dist.  Distance is always computed by first computing the distance^2, and then taking the square root.  So if the distance^2 overflows, the square root will be erroneous as well.  

You're right, I guess the case in my memory was about a sum
of distances^2 vs. a sum of net distances (area computation?)

**Pull request merged**
