### PR TITLE
Fix OffsetCurve parameter handling

### LINKED ISSUE #897: Offset curve has Weird Geometry
Output of offsetting this curve by 15 with CAP_ROUND and JOIN_ROUND is unexpected 
```
LINESTRING(292671.05 7336734.42,292624.85 7336739.72,292623.53 7336739.92,292622.36 7336740.2,292621.35 7336740.57,292620.94 7336740.78,292620.61 7336740.97,292620.33 7336741.14,292620.13 7336741.29,292619.79 7336741.57,292619.48 7336741.86,292619.34 7336742.01,292619.21 7336742.17,292619.09 7336742.34,292618.98 7336742.51,292618.8 7336742.88,292618.63 7336743.25,292618.57 7336743.43,292618.52 7336743.58,292618.48 7336743.71,292618.46 7336743.8,292618.44 7336743.98,292618.42 7336744.15,292618.41 7336744.33,292618.4 7336744.51,292618.39 7336744.69,292618.38 7336744.88,292618.38 7336744.91,292618.38 7336744.95,292618.38 7336744.99,292618.38 7336745.02,292618.38 7336745.06,292618.38 7336745.1,292618.38 7336745.13,292618.38 7336745.17,292618.38 7336745.21,292618.38 7336745.25,292618.38 7336745.43,292618.41 7336746.92)
```

Which gives 

```
LINESTRING(292672.7595667329 7336749.322260955,292626.8289702739 7336754.5913553545,292626.5791762319 7336754.629202936,292626.5097220095 7336754.654646562,292626.50454360223 7336754.64051091,292626.4042523117 7336754.65570656,292626.5015777726 7336754.632414997,292626.44602173776 7336754.480762037,292628.06232136535 7336753.77393037,292629.15317889326 7336753.036285378,292629.3464127592 7336752.884382651,292629.7456107097 7336752.533905098,292630.23746757495 7336752.041483207,292630.77071670454 7336751.429334497,292631.26624786 7336750.77544772,292631.44290077855 7336750.514153615,292632.18637824676 7336749.195972605,292632.6413907597 7336748.0441531595,292632.7640483846 7336747.639042543,292632.95704258484 7336746.627106525)
```

And looks like
Screenshot 2023-05-08 at 10 04 16 AM

Is this expected behaviour?

### PR DESCRIPTION
**Pull request by dr-jts**
Fixes `OffsetCurve` to ignore the value of `BufferParmeters.endCapStyle` and always use CAP_ROUND.
Also removes the unnecessary setting of this value in `GEOSOffsetCurve_r`.

Fixes #897

### CODE REVIEW

**Comment by strk** [comment]
Should it have always used CAP_FLAT instead ?

**Comment by strk** [comment]
See https://github.com/qgis/QGIS/issues/53165#issuecomment-1563214857

**Comment by dr-jts** [comment]
From the issue in https://github.com/qgis/QGIS/issues/53165 it appears that using Quadrant Segments = 0 (or any small value) causes artifacts to appear.  The QuadrantSegments value should be forced to be >= 8 when building offset curves.

**Comment by dr-jts** [comment]
See https://github.com/locationtech/jts/issues/980

**Pull request merged**
