### PR TITLE
GeosOp.cpp: minor fix explode description

### PR DESCRIPTION
**Pull request by mdsumner**

### CODE REVIEW

**Comment by mwtoews** [comment]
Could the typos also be fixed in [util/geosop/README.md](https://github.com/libgeos/geos/blob/main/util/geosop/README.md) too?

**Comment by mdsumner** [comment]
oh sure, sorry I assumed this was auto generated from the source - will.do

**Review by mwtoews — APPROVED** [review]
Thanks!

**Comment by mwtoews** [comment]
Cherry-picked to 3.10 a74e8ee5dc5772ccdc6a3af7901005363bea8654 and 3.9 199fc0b03c7860e0daafa2c9684efe79fc16a79a

**Pull request merged**
