### PR TITLE
Allow re-use of IndexedFacetDistance by exposing creator, destroyer, and distance method to c api

### PR DESCRIPTION
**Pull request by nyalldawson**
If deemed the correct approach to use, I'll go ahead and add unit tests...

### CODE REVIEW

**Comment by dbaston** [comment]
Hi Nyall,

Thanks for putting this together. I was talking with @dr-jts about this a week or two ago. What do you think about the idea of storing a lazily-initialized `IndexedFacetDistance` within a `PreparedGeometry` and then exposing this at the CAPI as `GEOSPreparedDistance` ? (or maybe `GEOSPreparedBoundaryDistance`, which would cover the case of distance between a test point and a polygon boundary). This would allow us to keep the C API a little higher-level and leave us free to implement various distance optimizations on prepared geometries in the future.

**Comment by nyalldawson** [comment]
@dbaston ok, I'll take a look...

**Comment by pramsey** [comment]
Trying a new approach?

**Comment by nyalldawson** [comment]
This is redundant now

**Pull request closed without merging**
