### PR TITLE
Port IsValidOp improvements from JTS

### PR DESCRIPTION
**Pull request by pramsey**
Port of https://github.com/locationtech/jts/pull/743 and https://github.com/locationtech/jts/pull/748.

### CODE REVIEW

**Comment by dbaston** [comment]
I'm seeing a pretty big performance regression on my Australia test-case:

main:
```
➜  cmake-build-release git:(main) bin/perf_unary ~/data/australia.txt valid
Reading geometries from /home/dan/data/australia.txt
Read 1 geometries.
625,265 usec
```

This PR:
```
➜  cmake-build-release git:(c7d40c15f) bin/perf_unary ~/data/australia.txt valid
Reading geometries from /home/dan/data/australia.txt
Read 1 geometries.
21,245,292 usec
```

**Comment by pramsey** [comment]
Ew. Supposed to be faster... hopefully I have some terrible hotspot that'll show up in profile. Also, I'm sure @dr-jts will check your case in JTS and see if it's an algorithmic woopsie.

**Comment by dbaston** [comment]
```
➜  jts git:(master) ✗ bin/jtsop.sh -time -a ~/data/australia.txt isValid
	
Operations: 1  Total Time: 78.8 s
```

Maybe the new algorithm removes some of the indexing that GEOS was using? e.g. https://github.com/libgeos/geos/pull/256

**Comment by dbaston** [comment]
Here's my data. Nothing special, just an extract from GADM.
[australia.txt.gz](https://github.com/libgeos/geos/files/6742780/australia.txt.gz)

**Comment by dr-jts** [comment]
> Maybe the new algorithm removes some of the indexing that GEOS was using? e.g. #256

That could well be it.  The Nested Shells check in the new IsValidOp code is using a nested loop, so is O(n^2).  Easy to fix.  I will look at that ASAP.

**Comment by dr-jts** [comment]
JTS has added `IndexedNestedPolygonTester` to improve performance of that check,  See [JTS-755](https://github.com/locationtech/jts/pull/755).

**Comment by pramsey** [comment]
Merged at https://github.com/libgeos/geos/commit/e151d238c16578b5474024526632382ecd10ecf2

**Pull request closed without merging**
